Repository ministryofjustice/cfe-civil, pull requests merged in 2023-06, with the labels that each got.

#160 Refactored saving of bank holiday dates to make sure they are cached …
  app/models/bank_holiday.rb
  spec/models/bank_holiday_spec.rb
Labels: question

#163 LEP-183 Redact dates of birth for applicant/partner and their dependants
  app/controllers/application_controller.rb
  app/services/request_logger.rb
  features/step_definitions/api_request.rb
  features/support/request_support_methods.rb
  spec/requests/v6/assessments_controller_spec.rb
Labels: approved

#168 Fix applicant and partner factories so they are less time-sensitive
  spec/factories/applicant_factory.rb
  spec/factories/partner_factory.rb
Labels: approved

#167 LEP-204 make tax and NI negatives
  app/services/workflows/non_passported_workflow.rb
  features/employment/self_employment.feature
  spec/fixtures/partner_financials.json
  spec/requests/swagger_docs/v6/full_assessment_spec.rb
  spec/requests/v6/assessments_controller_spec.rb
  spec/services/calculators/employment_monthly_value_calculator_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
  spec/swagger_helper.rb
  swagger/v6/swagger.yaml
Labels: approved

#175 LEP-207 PersonCapitalSubtotals refactor
  app/lib/person_capital_subtotals.rb
  app/services/assessors/capital_item_assessor.rb
  app/services/assessors/liquid_capital_assessor.rb
  app/services/assessors/non_liquid_capital_assessor.rb
  app/services/collators/capital_collator.rb
  spec/services/assessors/liquid_capital_assessor_spec.rb
  spec/services/assessors/non_liquid_capital_assessor_spec.rb
Labels: approved

#174 LEP-207 return vehicle in response
  app/lib/calculation_output.rb
  app/lib/capital_subtotals.rb
  app/lib/person_capital_subtotals.rb
  app/services/capital_collator_and_assessor.rb
  app/services/workflows/main_workflow.rb
  app/services/workflows/non_passported_workflow.rb
  spec/services/decorators/v6/assessment_decorator_spec.rb
  spec/services/workflows/main_workflow_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
  spec/services/workflows/passported_workflow_spec.rb
  spec/spec_helper.rb
Labels: approved

#177 LEP-206 re-enable sentry on UAT
  deploy/helm/values/production.yaml
  deploy/helm/values/staging.yaml
  deploy/helm/values/uat.yaml
Labels: approved

#173 LEP-201 add Cucumber tests for tax refund and multiple employments
  features/employment/tax_refunds.feature
  features/step_definitions/api_request.rb
  features/step_definitions/remarks.rb
  features/support/response_support_methods.rb
Labels: approved

#178 Grafana dashboard fixes copied from CCQ
  infrastructure/uat/ingress-dashboard.yaml
  infrastructure/uat/pods-dashboard.yaml
Labels: approved

#179 LEP-212 support annual income frequency for self employment
  app/models/self_employment_income.rb
  app/services/utilities/monthly_amount_converter.rb
  spec/services/workflows/non_passported_workflow_spec.rb
  swagger/v6/swagger.yaml
Labels: approved

#176 LEP-172 remarks for partner variations to match those for applicant
  app/services/concerns/exemptable.rb
  app/services/remark_generators/amount_variation_checker.rb
  app/services/remark_generators/base_checker.rb
  app/services/remark_generators/frequency_checker.rb
  app/services/remark_generators/multi_benefit_checker.rb
  app/services/remark_generators/orchestrator.rb
  app/services/remark_generators/residual_balance_checker.rb
  app/services/workflows/main_workflow.rb
  spec/requests/v6/assessments_controller_spec.rb
  spec/services/remark_generators/amount_variation_checker_spec.rb
  spec/services/remark_generators/frequency_checker_spec.rb
  spec/services/remark_generators/multi_benefit_checker_spec.rb
  spec/services/remark_generators/orchestrator_spec.rb
  spec/services/remark_generators/residual_balance_checker_spec.rb
  spec/services/workflows/main_workflow_spec.rb
  spec/spec_helper.rb
Labels: approved

#165 Lep 191 applicant and partner tables
  app/controllers/v6/assessments_controller.rb
  app/lib/person_disposable_income_subtotals.rb
  app/lib/person_wrapper.rb
  app/models/applicant.rb
  app/models/assessment.rb
  app/models/disposable_income_summary.rb
  app/models/partner.rb
  app/models/person_data.rb
  app/services/assessors/assessment_proceeding_type_assessor.rb
  app/services/assessors/main_assessor.rb
  app/services/base_workflow_service.rb
  app/services/calculators/pensioner_capital_disregard_calculator.rb
  app/services/capital_collator_and_assessor.rb
  app/services/creators/applicant_creator.rb
  app/services/creators/full_assessment_creator.rb
  app/services/creators/partner_financials_creator.rb
  app/services/decorators/v6/assessment_decorator.rb
  app/services/decorators/v6/disposable_income_result_decorator.rb
  app/services/decorators/v6/gross_income_decorator.rb
  app/services/decorators/v6/result_summary_decorator.rb
  app/services/workflows/main_workflow.rb
  app/services/workflows/non_passported_workflow.rb
  app/services/workflows/passported_workflow.rb
  config/locales/en.yml
  db/migrate/20230606141257_remove_applicant_and_partner_tables.rb
  db/schema.rb
  spec/factories/applicant_factory.rb
  spec/factories/assessment_factory.rb
  spec/factories/capital_summary_factory.rb
  spec/factories/disposable_income_summary_factory.rb
  spec/factories/gross_income_summary_factory.rb
  spec/factories/partner_factory.rb
  spec/models/applicant_spec.rb
  spec/requests/v6/assessments_controller_spec.rb
  spec/services/assessors/assessment_proceeding_type_assessor_spec.rb
  spec/services/assessors/main_assessor_spec.rb
  spec/services/calculators/dependant_allowance_calculator_spec.rb
  spec/services/calculators/pensioner_capital_disregard_calculator_spec.rb
  spec/services/collators/capital_collator_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
  spec/services/collators/outgoings_collator_spec.rb
  spec/services/collators/regular_outgoings_collator_spec.rb
  spec/services/creators/applicant_creator_spec.rb
  spec/services/creators/partner_financials_creator_spec.rb
  spec/services/cull_stale_assessments_service_spec.rb
  spec/services/decorators/v6/applicant_decorator_spec.rb
  spec/services/decorators/v6/assessment_decorator_spec.rb
  spec/services/decorators/v6/disposable_income_result_decorator_spec.rb
  spec/services/workflows/main_workflow_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
  spec/services/workflows/passported_workflow_spec.rb
Labels: approved

#184 LEP-213 add support for cfe-crime-dev
  infrastructure/uat/ingress-dashboard.yaml
  infrastructure/uat/pods-dashboard.yaml
Labels: ready for review

#182 LEP-214 empty main home and additional property
  app/lib/capital_subtotals.rb
  app/lib/person_capital_subtotals.rb
  app/lib/property_subtotals.rb
  app/models/property.rb
  app/services/assessors/property_assessor.rb
  app/services/calculators/property_calculator.rb
  app/services/capital_collator_and_assessor.rb
  app/services/collators/capital_collator.rb
  app/services/decorators/v6/capital_decorator.rb
  app/services/decorators/v6/property_decorator.rb
  app/services/workflows/main_workflow.rb
  app/services/workflows/non_passported_workflow.rb
  spec/requests/v6/assessments_controller_spec.rb
  spec/services/assessors/property_assessor_spec.rb
  spec/services/collators/capital_collator_spec.rb
  spec/services/decorators/v6/assessment_decorator_spec.rb
  spec/services/decorators/v6/property_decorator_spec.rb
  spec/services/workflows/passported_workflow_spec.rb
  spec/swagger_helper.rb
  swagger/v6/swagger.yaml
Labels: approved

#187 Fix bracket in Grafana dashboard
  infrastructure/uat/pods-dashboard.yaml
Labels: approved

#169 LEP-145 convert relationship: child_relative to DOB check
  app/models/dependant.rb
  app/services/calculators/childcare_eligibility_calculator.rb
  app/services/creators/gross_income_eligibility_creator.rb
  spec/models/dependant_spec.rb
  spec/services/calculators/childcare_eligibility_calculator_spec.rb
Labels: approved

#191 LEP-216 deployment is done on automatic schedule
  .circleci/config.yml
Labels: ready for review

#188 LEP-218 self employment rework
  app/controllers/v6/assessments_controller.rb
  app/lib/employment_income_subtotals.rb
  app/lib/person_gross_income_subtotals.rb
  app/models/employment_income.rb
  app/models/employment_or_self_employment_income.rb
  app/models/person_data.rb
  app/models/self_employment_income.rb
  app/services/calculators/employment_income_calculator.rb
  app/services/calculators/multiple_employments_calculator.rb
  app/services/collators/gross_income_collator.rb
  app/services/decorators/v6/assessment_decorator.rb
  app/services/decorators/v6/gross_income_decorator.rb
  app/services/workflows/non_passported_workflow.rb
  features/employment/self_employment.feature
  features/step_definitions/api_request.rb
  features/step_definitions/self_employment.rb
  spec/factories/person_details_factory.rb
  spec/requests/swagger_docs/v6/full_assessment_spec.rb
  spec/requests/v6/assessments_controller_spec.rb
  spec/services/calculators/employment_income_calculator_spec.rb
  spec/services/calculators/multiple_employments_calculator_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
  spec/services/decorators/v6/assessment_decorator_spec.rb
  spec/services/decorators/v6/gross_income_decorator_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
  spec/spec_helper.rb
  spec/swagger_helper.rb
  swagger/v6/swagger.yaml
Labels: approved

#193 Reword bug description
  Changelog.md
Labels: approved

#196 LEP-223 Rescue KeyError (key not found: "applicant")
  app/services/request_logger.rb
  spec/requests/v6/assessments_controller_spec.rb
Labels: approved

#198 LEP-223 Fix partner dob redact
  app/services/request_logger.rb
  spec/requests/v6/assessments_controller_spec.rb
Labels: approved

#199 Lep 203 bank holiday call with faraday to avoid db table
  Gemfile
  Gemfile.lock
  app/models/bank_holiday.rb
  app/services/govuk_bank_holiday_retriever.rb
  app/services/utilities/calendar_monthly_period_analyser.rb
  app/services/utilities/working_day_calculator.rb
  db/migrate/20230629124618_drop_bank_holidays.rb
  db/schema.rb
  spec/cassettes/IntegrationTests_TestRunner/run_integration_tests/processes_all_the_tests_on_all_the_sheets.yml
  spec/integration/policy_disregards_spec.rb
  spec/integration/remarks_spec.rb
  spec/integration/test_runner_spec.rb
  spec/models/bank_holiday_spec.rb
  spec/services/calculators/state_benefits_calculator_spec.rb
  spec/services/collators/childcare_collator_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
  spec/services/collators/housing_costs_collator_spec.rb
  spec/services/collators/legal_aid_collator_spec.rb
  spec/services/collators/maintenance_collator_spec.rb
  spec/services/govuk_bank_holiday_retriever_spec.rb
  spec/services/remark_generators/frequency_checker_spec.rb
  spec/services/remark_generators/orchestrator_spec.rb
  spec/services/utilities/calendar_monthly_period_analyser_spec.rb
  spec/services/utilities/regular_period_analyser_spec.rb
Labels: approved
