Repository ministryofjustice/cfe-civil, pull requests merged in 2023-09, with the labels that each got.

#293 LEP-322 disassociate properties from capital_summary
  app/controllers/v6/assessments_controller.rb
  app/lib/capital_subtotals.rb
  app/models/capital_summary.rb
  app/models/capitals_data.rb
  app/models/property.rb
  app/services/assessors/property_assessor.rb
  app/services/capital_collator_and_assessor.rb
  app/services/collators/capital_collator.rb
  app/services/creators/full_assessment_creator.rb
  app/services/creators/partner_financials_creator.rb
  app/services/creators/partner_properties_creator.rb
  app/services/creators/properties_creator.rb
  app/services/workflows/main_workflow.rb
  app/services/workflows/non_passported_workflow.rb
  db/migrate/20230829105118_remove_properties_table.rb
  db/schema.rb
  spec/factories/assessment_factory.rb
  spec/factories/capital_summary_factory.rb
  spec/factories/person_details_factory.rb
  spec/factories/property_factory.rb
  spec/models/capital_summary_spec.rb
  spec/requests/v6/assessments_controller/simple_spec.rb
  spec/services/assessors/property_assessor_spec.rb
  spec/services/collators/capital_collator_spec.rb
  spec/services/creators/partner_financials_creator_spec.rb
  spec/services/creators/properties_creator_spec.rb
  spec/services/cull_stale_assessments_service_spec.rb
  spec/services/decorators/v6/assessment_decorator_spec.rb
  spec/services/decorators/v6/property_decorator_spec.rb
  spec/services/workflows/main_workflow_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
  spec/services/workflows/passported_workflow_spec.rb
Labels: ready for review, Do Not Merge

#302 LEP-322 - add new test for NI and tax refunds
  spec/requests/v6/assessments_controller/simple_spec.rb
Labels: approved

#303 Pull Request template - migration reminder, checkboxes
  docs/pull_request_template.md
Labels: approved

#300 fix rollback migration bug
  db/migrate/20230822150822_remove_capital_items_table.rb
Labels: approved

#307 LEP-320 suggested tidy up
  app/services/calculators/dependant_allowance_calculator.rb
  spec/services/calculators/dependant_allowance_calculator_spec.rb
Labels: approved

#305 LEP-320 - deducted child_under_15's income from dependent allowance
  app/services/calculators/dependant_allowance_calculator.rb
  features/dependant/dependant_income.feature
  features/dependant/dependant_monthly_income.feature
  spec/requests/v6/assessments_controller/simple_spec.rb
  spec/services/calculators/dependant_allowance_calculator_spec.rb
Labels: ready for review

#306 added test for LEP-322
  spec/requests/v6/assessments_controller/simple_spec.rb
Labels: approved

#304 Lep 322 return payment data
  app/lib/employment_income_subtotals.rb
  app/services/calculators/employment_income_calculator.rb
  app/services/calculators/employment_monthly_value_calculator.rb
  app/services/calculators/multiple_employments_calculator.rb
  app/services/calculators/tax_ni_refund_calculator.rb
  app/services/collators/gross_income_collator.rb
  app/services/decorators/v6/gross_income_decorator.rb
  app/services/workflows/non_passported_workflow.rb
  spec/services/calculators/multiple_employments_calculator_spec.rb
  spec/services/calculators/tax_ni_refund_calculator_spec.rb
  spec/services/decorators/v6/gross_income_decorator_spec.rb
Labels: approved

#313 LEP-334 split out Applicant part of GrossIncomeResult decorator
  app/services/decorators/v6/applicant_gross_income_result_decorator.rb
  app/services/decorators/v6/gross_income_result_decorator.rb
  app/services/decorators/v6/result_summary_decorator.rb
  spec/services/decorators/v6/applicant_gross_income_result_decorator_spec.rb
Labels: approved

#314 LEP-334 partial: proceeding_type_summarizer refactor
  app/services/summarizers/assessment_proceeding_type_summarizer.rb
  spec/services/summarizers/assessment_proceeding_type_summarizer_spec.rb
Labels: approved

#299 LEP-332 remove employments and employment_payments from DB
  app/controllers/v6/assessments_controller.rb
  app/models/assessment.rb
  app/models/employment.rb
  app/models/employment_payment.rb
  app/models/person_data.rb
  app/services/creators/employments_creator.rb
  app/services/creators/full_assessment_creator.rb
  app/services/creators/partner_financials_creator.rb
  app/services/decorators/v6/assessment_decorator.rb
  app/services/workflows/main_workflow.rb
  app/services/workflows/non_passported_workflow.rb
  db/migrate/20220317185108_make_client_id_mandatory.rb
  db/migrate/20230904170037_remove_employments_and_employment_payments_tables.rb
  db/schema.rb
  spec/factories/assessment_factory.rb
  spec/factories/employment_factory.rb
  spec/factories/employment_payment_factory.rb
  spec/factories/gross_income_summary_factory.rb
  spec/factories/person_details_factory.rb
  spec/services/calculators/employment_monthly_value_calculator_spec.rb
  spec/services/calculators/multiple_employments_calculator_spec.rb
  spec/services/calculators/tax_ni_refund_calculator_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
  spec/services/creators/employments_creator_spec.rb
  spec/services/creators/partner_financials_creator_spec.rb
  spec/services/cull_stale_assessments_service_spec.rb
  spec/services/decorators/v6/assessment_decorator_spec.rb
  spec/services/decorators/v6/gross_income_decorator_spec.rb
  spec/services/remark_generators/frequency_checker_spec.rb
  spec/services/remark_generators/orchestrator_spec.rb
  spec/services/utilities/employment_income_monthly_equivalent_calculator_spec.rb
  spec/services/utilities/employment_income_variation_checker_spec.rb
  spec/services/workflows/main_workflow_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
Labels: approved

#308 LEP-343 Return assessment_result from calculation_output instead of DB
  app/lib/calculation_output.rb
  app/services/decorators/v6/assessment_decorator.rb
  app/services/decorators/v6/remarks_decorator.rb
  app/services/decorators/v6/result_summary_decorator.rb
  app/services/summarizers/main_summarizer.rb
  app/services/workflows/main_workflow.rb
  app/services/workflows/non_passported_workflow.rb
  app/services/workflows/passported_workflow.rb
  db/migrate/20230911161839_remove_column_assessment_result_from_assessments.rb
  db/schema.rb
  spec/services/decorators/v6/assessment_decorator_spec.rb
  spec/services/summarizers/main_summarizer_spec.rb
  spec/services/workflows/main_workflow_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
  spec/services/workflows/passported_workflow_spec.rb
Labels: approved

#317 LEP-246 MTR phase 2 increase pensioner disregard age
  app/services/calculators/pensioner_capital_disregard_calculator.rb
  app/services/calculators/state_pension_date_calculator.rb
  config/thresholds/mtr-2026.yml
  spec/factories/applicant_factory.rb
  spec/services/calculators/pensioner_capital_disregard_calculator_spec.rb
  spec/services/calculators/state_pension_date_calculator_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
Labels: ready for review

#315 Example request is filled out more, to demo all the "partner" fields
  spec/fixtures/partner_financials.json
  swagger/v6/swagger.yaml
  swagger/v7/swagger.yaml
Labels: approved

#323 LEP-239 Increase fixed employment allowance
  config/thresholds/mtr-2026.yml
  features/mtr/employment_allowance.feature
  features/step_definitions/api_request.rb
  spec/models/threshold_spec.rb
Labels: approved

#325 LEP-194-195 MTR: remove special cases for immigration and asylum
  app/services/creators/capital_eligibility_creator.rb
  app/services/creators/disposable_income_eligibility_creator.rb
  config/thresholds/mtr-2026.yml
  features/mtr/immigration_and_asylum.feature
  features/step_definitions/api_request.rb
  features/support/response_support_methods.rb
  spec/services/creators/capital_eligibility_creator_spec.rb
  spec/services/creators/disposable_income_eligibility_creator_spec.rb
Labels: approved

#324 LEP-233 New gross income threshold raising
  Changelog.md
  app/models/dependant.rb
  app/services/creators/gross_income_eligibility_creator.rb
  config/thresholds/2018-04-08.yml
  config/thresholds/2019-04-08.yml
  config/thresholds/2020-04-06.yml
  config/thresholds/2021-01-28.yml
  config/thresholds/2021-04-12.yml
  config/thresholds/2022-04-11.yml
  config/thresholds/2023-04-10.yml
  config/thresholds/mtr-2026.yml
  spec/services/creators/gross_income_eligibility_creator_spec.rb
  spec/spec_helper.rb
Labels: approved

#327 LEP-245 Increase Property Disregard Main Home Threshold
  config/thresholds/mtr-2026.yml
  features/mtr/property_disregard_main_home.feature
  spec/models/threshold_spec.rb
Labels: approved

#329 LEP-236 remove housing cost cap
  config/thresholds/mtr-2026.yml
  features/mtr/housing_cost_cap.feature
  features/support/response_support_methods.rb
Labels: approved

#330 LEP-248 Remove cap on SMOD
  config/thresholds/mtr-2026.yml
  features/mtr/subject_matter_of_dispute_disregard.feature
  spec/models/threshold_spec.rb
Labels: approved

#332 LEP-233 added cucumber test
  features/CCC_CFE_Integration_Test_V3/NPE10-4-V5.feature
  features/mtr/equivilization.feature
  features/partner/partner_assessment.feature
  features/step_definitions/api_request.rb
Labels: ready for review

#331 LEP-246 Add spec
  features/mtr/pensioner_capital_disregard.feature
  features/step_definitions/api_request.rb
Labels: approved

#334 LEP-232 Increase disposable income thresholds
  config/thresholds/mtr-2026.yml
  features/mtr/immigration_and_asylum.feature
  spec/models/threshold_spec.rb
Labels: approved

#336 LEP-257 add documentation for main home in DA cases
  app/lib/swagger_docs.rb
  spec/requests/swagger_docs/v6/full_assessment_spec.rb
  spec/requests/swagger_docs/v7/full_assessment_spec.rb
  swagger/v6/swagger.yaml
  swagger/v7/swagger.yaml
Labels: approved

#335 LEP-235 MTR lone parent allowance
  app/lib/person_disposable_income_subtotals.rb
  app/lib/swagger_docs.rb
  app/models/dependant.rb
  app/services/calculators/lone_parent_allowance_calculator.rb
  app/services/collators/disposable_income_collator.rb
  app/services/collators/outgoings_collator.rb
  app/services/decorators/v6/applicant_disposable_income_result_decorator.rb
  app/services/workflows/non_passported_workflow.rb
  config/thresholds/mtr-2026.yml
  features/mtr/dependant_allowance.feature
  spec/requests/v6/assessments_controller/simple_spec.rb
  spec/services/collators/outgoings_collator_spec.rb
  spec/services/decorators/v6/disposable_income_result_decorator_spec.rb
  swagger/v6/swagger.yaml
  swagger/v7/swagger.yaml
Labels: approved

#343 LEP-241 Update swagger description for "benefits"
  app/lib/swagger_docs.rb
  swagger/v6/swagger.yaml
  swagger/v7/swagger.yaml
Labels: approved

#341 LEP-237 - Add category "pension_contribution"
  app/constants/cfe_constants.rb
  app/lib/person_disposable_income_subtotals.rb
  app/lib/swagger_docs.rb
  app/models/disposable_income_summary.rb
  app/models/outgoings/pension_contribution.rb
  app/models/regular_transaction.rb
  app/services/calculators/housing_costs_calculator.rb
  app/services/calculators/monthly_cash_transaction_amount_calculator.rb
  app/services/calculators/monthly_regular_transaction_amount_calculator.rb
  app/services/calculators/pension_contribution_calculator.rb
  app/services/collators/childcare_collator.rb
  app/services/collators/disposable_income_collator.rb
  app/services/collators/gross_income_collator.rb
  app/services/collators/outgoings_collator.rb
  app/services/decorators/v6/disposable_income_decorator.rb
  app/services/workflows/non_passported_workflow.rb
  config/thresholds/mtr-2026.yml
  features/mtr/pension_contribution/cash_transactions.feature
  features/mtr/pension_contribution/outgoings.feature
  features/mtr/pension_contribution/regular_transactions.feature
  features/step_definitions/api_request.rb
  features/support/response_support_methods.rb
  spec/factories/outgoing_factory.rb
  spec/factories/regular_transaction_factory.rb
  spec/requests/v6/assessments_controller/simple_spec.rb
  spec/services/calculators/pension_contribution_calculator_spec.rb
  swagger/v6/swagger.yaml
  swagger/v7/swagger.yaml
Labels: approved

#346 add tag to pension calculator unit test
  spec/services/calculators/pension_contribution_calculator_spec.rb
Labels: approved

#344 Refactor of Regular transactions calculator
  app/constants/cfe_constants.rb
  app/lib/person_disposable_income_subtotals.rb
  app/models/regular_transaction.rb
  app/services/calculators/housing_costs_calculator.rb
  app/services/calculators/monthly_equivalent_calculator.rb
  app/services/calculators/monthly_regular_transaction_amount_calculator.rb
  app/services/calculators/pension_contribution_calculator.rb
  app/services/collators/gross_income_collator.rb
  app/services/collators/outgoings_collator.rb
  app/services/collators/regular_outgoings_collator.rb
  app/services/utilities/payment_period_data_extractor.rb
  features/mtr/housing_cost_cap.feature
  features/step_definitions/api_request.rb
  features/support/response_support_methods.rb
  spec/factories/cash_transaction_category_factory.rb
  spec/factories/regular_transaction_factory.rb
  spec/factories/state_benefit_payment_factory.rb
  spec/services/utilities/payment_period_data_extractor_spec.rb
Labels: approved

#337 LEP-255 MTR income contributions
  app/services/calculators/income_contribution_calculator.rb
  config/thresholds/mtr-2026.yml
  features/mtr/income_contributions.feature
  features/step_definitions/api_request.rb
  spec/services/calculators/income_contribution_calculator_spec.rb
Labels: approved

#345 Refactor of housing cost calculator test
  app/models/outgoings/housing_cost.rb
  app/services/calculators/housing_costs_calculator.rb
  app/services/collators/housing_costs_collator.rb
  spec/factories/cash_transaction_category_factory.rb
  spec/services/calculators/housing_costs_calculator_spec.rb
Labels: approved

#338 LEP-256 MTR contribution minimum
  app/lib/capital/base.rb
  app/lib/capital/subtotals.rb
  app/lib/disposable_income/base.rb
  app/lib/disposable_income/subtotals.rb
  app/lib/disposable_income/unassessed.rb
  app/lib/employment_income_subtotals.rb
  app/lib/gross_income_category_subtotals.rb
  app/lib/person_disposable_income_subtotals.rb
  app/lib/person_gross_income_subtotals.rb
  app/services/calculators/income_contribution_calculator.rb
  app/services/collators/gross_income_collator.rb
  app/services/workflows/non_passported_workflow.rb
  config/thresholds/2018-04-08.yml
  config/thresholds/2019-04-08.yml
  config/thresholds/2020-04-06.yml
  config/thresholds/2021-01-28.yml
  config/thresholds/2021-04-12.yml
  config/thresholds/2022-04-11.yml
  config/thresholds/2023-04-10.yml
  config/thresholds/mtr-2026.yml
  features/mtr/gross_income.feature
  features/mtr/income_contributions.feature
  features/mtr/pensioner_disregard.feature
  spec/lib/disposable_income/subtotals_spec.rb
  spec/services/calculators/income_contribution_calculator_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
Labels: approved

#348 LEP-391 fix up example JSON file from swagger doc
  spec/fixtures/partner_financials.json
  swagger/v6/swagger.yaml
  swagger/v7/swagger.yaml
Labels: approved

#350 LEP-249 Add note about inaccessible capital
  app/lib/swagger_docs.rb
  swagger/v6/swagger.yaml
  swagger/v7/swagger.yaml
Labels: approved
