Repository ministryofjustice/cfe-civil, pull requests merged in 2023-04, with the labels that each got.

#42 LEP-39 circle config for staging and production
  .circleci/config.yml
  deploy/helm/values/production.yaml
  deploy/helm/values/staging.yaml
Labels: ready for review

#71 Lep 91 remove unused assessment errors table
  app/models/assessment.rb
  app/services/calculators/housing_costs_calculator.rb
  app/services/calculators/monthly_equivalent_calculator.rb
  app/services/calculators/monthly_income_converter.rb
  app/services/calculators/state_benefits_calculator.rb
  app/services/collators/childcare_collator.rb
  app/services/collators/gross_income_collator.rb
  app/services/collators/legal_aid_collator.rb
  app/services/collators/maintenance_collator.rb
  app/services/collators/outgoings_collator.rb
  db/migrate/20230414114501_drop_assessment_errors.rb
  db/schema.rb
  spec/services/calculators/monthly_income_converter_spec.rb
  spec/services/collators/childcare_collator_spec.rb
  spec/services/cull_stale_assessments_service_spec.rb
Labels: question

#74 Remove unused code
  app/services/creators/properties_creator.rb
  app/services/utilities/calculation_period.rb
  app/services/utilities/matter_type_finder.rb
  spec/services/utilities/calculation_period_spec.rb
  spec/services/utilities/matter_type_finder_spec.rb
  spec/spec_helper.rb
Labels: approved

#76 Lep 99 rework
  app/lib/calculation_output.rb
  app/lib/capital_subtotals.rb
  app/lib/person_capital_subtotals.rb
  app/services/assessors/liquid_capital_assessor.rb
  app/services/assessors/non_liquid_capital_assessor.rb
  app/services/assessors/vehicle_assessor.rb
  app/services/calculators/property_calculator.rb
  app/services/calculators/subject_matter_of_dispute_disregard_calculator.rb
  app/services/capital_collator_and_assessor.rb
  app/services/collators/capital_collator.rb
  app/services/decorators/v5/applicant_capital_result_decorator.rb
  spec/factories/property_factory.rb
  spec/factories/vehicle_factory.rb
  spec/lib/person_capital_subtotals_spec.rb
  spec/services/assessors/liquid_capital_assessor_spec.rb
  spec/services/assessors/non_liquid_capital_assessor_spec.rb
  spec/services/calculators/subject_matter_of_dispute_disregard_calculator_spec.rb
  spec/services/collators/capital_collator_spec.rb
  spec/services/decorators/v5/applicant_capital_result_decorator_spec.rb
  spec/services/decorators/v5/assessment_decorator_spec.rb
  spec/services/workflows/passported_workflow_spec.rb
Labels: approved

#77 Lep 100 expose total dependant allowance for under and over 16 year olds
  app/lib/calculation_output.rb
  app/lib/dependant_wrapper.rb
  app/lib/disposable_income_subtotals.rb
  app/lib/person_disposable_income_subtotals.rb
  app/lib/person_wrapper.rb
  app/services/calculators/dependant_allowance_calculator.rb
  app/services/collators/dependants_allowance_collator.rb
  app/services/collators/disposable_income_collator.rb
  app/services/collators/outgoings_collator.rb
  app/services/decorators/v5/assessment_decorator.rb
  app/services/decorators/v5/disposable_income_decorator.rb
  app/services/decorators/v5/disposable_income_result_decorator.rb
  app/services/decorators/v5/result_summary_decorator.rb
  app/services/workflows/non_passported_workflow.rb
  spec/factories/dependant_factory.rb
  spec/requests/swagger_docs/v5/full_assessment_spec.rb
  spec/requests/v6/assessments_controller_spec.rb
  spec/services/calculators/dependant_allowance_calculator_spec.rb
  spec/services/collators/dependants_allowance_collator_spec.rb
  spec/services/collators/disposable_income_collator_spec.rb
  spec/services/decorators/v5/disposable_income_result_decorator_spec.rb
  swagger/v5/swagger.yaml
Labels: approved

#94 Pin pg gem to < 1.5 due to rails incompatibility
  Gemfile
  Gemfile.lock
Labels: approved
