Repository ministryofjustice/cfe-civil, pull requests merged in 2023-11, with the labels that each got.

#394 LEP-240 Add 'priority_debt_repayment' category for outgoings, cash transactions and regular transactions
  app/constants/cfe_constants.rb
  app/lib/person_disposable_income_subtotals.rb
  app/lib/swagger_docs.rb
  app/models/cash_transaction.rb
  app/models/gross_income_summary.rb
  app/models/outgoings/priority_debt_repayment.rb
  app/models/regular_transaction.rb
  app/services/calculators/housing_costs_calculator.rb
  app/services/calculators/priority_debt_repayment_calculator.rb
  app/services/collators/disposable_income_collator.rb
  app/services/collators/gross_income_collator.rb
  app/services/collators/outgoings_collator.rb
  app/services/decorators/v6/disposable_income_decorator.rb
  app/services/remark_generators/orchestrator.rb
  app/services/remark_generators/payment_checker.rb
  app/services/remarks.rb
  app/services/workflows/main_workflow.rb
  config/thresholds/mtr-2026.yml
  features/mtr/priority_debt_repayment.feature
  spec/factories/outgoing_factory.rb
  spec/factories/regular_transaction_factory.rb
  spec/models/cash_transaction_spec.rb
  spec/requests/v6/assessments_controller/simple_spec.rb
  spec/services/calculators/priority_debt_repayment_calculator_spec.rb
  spec/services/remark_generators/orchestrator_spec.rb
  spec/services/remark_generators/payment_checker_spec.rb
  spec/services/workflows/main_workflow_spec.rb
  swagger/v6/swagger.yaml
  swagger/v7/swagger.yaml
Labels: approved

#369 Dockerfile updated to Alpine 3.18 and cosmetic improvements
  Dockerfile
Labels: approved

#367 Updated shield/badge for MOJ Repo standards
  README.md
Labels: approved

#402 LEP-345 tidy up eligibility creators
  app/services/creators/capital_eligibility_creator.rb
  app/services/creators/disposable_income_eligibility_creator.rb
  app/services/creators/gross_income_eligibility_creator.rb
  spec/spec_helper.rb
Labels: approved

#398 Lep 345 remove pipeline duplication
  app/controllers/v6/assessments_controller.rb
  app/lib/calculation_output.rb
  app/lib/capital/base.rb
  app/lib/capital/subtotals.rb
  app/lib/capital/subtotals_with_partner.rb
  app/lib/capital/unassessed.rb
  app/lib/capital/unassessed_with_partner.rb
  app/lib/disposable_income/base.rb
  app/lib/disposable_income/subtotals.rb
  app/lib/disposable_income/unassessed.rb
  app/lib/eligibility_results.rb
  app/lib/gross_income/subtotals.rb
  app/lib/gross_income/unassessed.rb
  app/lib/person_gross_income_subtotals.rb
  app/models/person_data.rb
  app/services/calculators/state_benefits_calculator.rb
  app/services/capital_collator_and_assessor.rb
  app/services/collators/gross_income_collator.rb
  app/services/concerns/assessment_eligibility.rb
  app/services/decorators/v6/remarks_decorator.rb
  app/services/summarizers/assessment_proceeding_type_summarizer.rb
  app/services/summarizers/main_summarizer.rb
  app/services/workflows/main_workflow.rb
  app/services/workflows/non_passported_workflow.rb
  spec/requests/v6/assessments_controller/simple_spec.rb
  spec/services/calculators/state_benefits_calculator_spec.rb
  spec/services/decorators/v6/applicant_gross_income_result_decorator_spec.rb
  spec/services/decorators/v6/assessment_decorator_spec.rb
  spec/services/decorators/v6/gross_income_decorator_spec.rb
  spec/services/summarizers/assessment_proceeding_type_summarizer_spec.rb
  spec/services/summarizers/main_summarizer_spec.rb
  spec/services/workflows/main_workflow_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
  spec/spec_helper.rb
Labels: approved

#403 Lep 345 implementation
  app/lib/gross_income/subtotals.rb
  app/lib/gross_income/unassessed.rb
  app/models/eligibility/gross_income.rb
  app/services/creators/gross_income_eligibility_creator.rb
  app/services/workflows/main_workflow.rb
  app/services/workflows/non_passported_workflow.rb
  app/services/workflows/passported_workflow.rb
  config/thresholds/mtr-2026.yml
  features/mtr/gross_income_thresholds.feature
  features/mtr/subject_matter_of_dispute_disregard.feature
  features/support/response_support_methods.rb
  spec/lib/gross_income/unassessed_spec.rb
  spec/services/creators/gross_income_eligibility_creator_spec.rb
  spec/services/decorators/v6/applicant_gross_income_result_decorator_spec.rb
  spec/services/decorators/v6/proceeding_types_result_decorator_spec.rb
  spec/services/workflows/main_workflow_spec.rb
  spec/spec_helper.rb
Labels: approved

#413 Fix type in readme
  README.md
Labels: approved

#412 Add schema example for partner/other_incomes
  spec/fixtures/partner_financials.json
  swagger/v6/swagger.yaml
  swagger/v7/swagger.yaml
Labels: approved

#414 Run dependabot at 9am on Mondays
  .github/dependabot.yml
Labels: ready for review

#406 Lep 393 don't capture errors in test mode
  .circleci/config.yml
  app/controllers/application_controller.rb
  app/models/assessment.rb
  app/services/creators/assessment_creator.rb
  app/services/creators/full_assessment_creator.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/locales/en.yml
  spec/lib/disposable_income/subtotals_spec.rb
  spec/rails_helper.rb
  spec/requests/application_controller_spec.rb
  spec/requests/v6/assessments_controller/errors_spec.rb
  spec/requests/v6/assessments_controller/simple_spec.rb
  spec/services/calculators/council_tax_calculator_spec.rb
  spec/services/calculators/pension_contribution_calculator_spec.rb
  spec/services/calculators/priority_debt_repayment_calculator_spec.rb
  spec/services/remark_generators/orchestrator_spec.rb
  spec/spec_helper.rb
  spec/support/error_responses.rb
Labels: approved

#420 LEP-401 assessment stats
  app/lib/assessment_stats.rb
  spec/spec_helper.rb
Labels: approved

#421 LEP-344 don't count earning child in >4 children test
  app/models/dependant.rb
  app/services/calculators/dependant_allowance_calculator.rb
  app/services/calculators/lone_parent_allowance_calculator.rb
  app/services/creators/gross_income_eligibility_creator.rb
  features/employment/child_uplift.feature
Labels: approved

#407 fix cash transactions ordering
  app/models/gross_income_summary.rb
  spec/models/cash_transaction_spec.rb
  spec/models/gross_income_summary_spec.rb
Labels: approved

#423 LEP-243 housing benefit test clarification
  app/services/calculators/housing_costs_calculator.rb
  app/services/calculators/state_benefits_calculator.rb
  features/mtr/housing_benefit_disposable.feature
  features/mtr/housing_benefit_gross.feature
  features/step_definitions/api_request_steps.rb
Labels: approved

#429 LEP-409 remove code climate, restore undercover
  .circleci/config.yml
Labels: approved

#426 LEP-411 rename assessors to calculators
  .rubocop.yml
  README.md
  app/lib/capital/unassessed.rb
  app/lib/person_capital_subtotals.rb
  app/services/assessors/liquid_capital_assessor.rb
  app/services/assessors/non_liquid_capital_assessor.rb
  app/services/calculators/capital_item_calculator.rb
  app/services/calculators/liquid_capital_calculator.rb
  app/services/calculators/non_liquid_capital_calculator.rb
  app/services/calculators/property_calculator.rb
  app/services/calculators/vehicle_calculator.rb
  app/services/capital_collator_and_assessor.rb
  app/services/collators/capital_collator.rb
  app/services/workflows/non_passported_workflow.rb
  app/services/workflows/passported_workflow.rb
  spec/services/calculators/liquid_capital_calculator_spec.rb
  spec/services/calculators/non_liquid_capital_calculator_spec.rb
  spec/services/calculators/property_calculator_spec.rb
  spec/services/calculators/vehicle_calculator_spec.rb
  spec/services/collators/capital_collator_spec.rb
  spec/services/decorators/v6/property_decorator_spec.rb
Labels: approved

#427 LEP-402 Rename mtr/* file names
  features/mtr/mtr-45_housing_benefit_disposable.feature
  features/mtr/mtr_31_32_46_income_capital_thresholds.feature
  features/mtr/mtr_31_61_62_immigration_and_asylum.feature
  features/mtr/mtr_32_51_subject_matter_of_dispute_disregard.feature
  features/mtr/mtr_32_59_60_income_contributions.feature
  features/mtr/mtr_32_gross_income_thresholds.feature
  features/mtr/mtr_33_equivilization.feature
  features/mtr/mtr_34_35_dependant_allowance.feature
  features/mtr/mtr_36_housing_cost_cap.feature
  features/mtr/mtr_37_council_tax.feature
  features/mtr/mtr_39_41_employment.feature
  features/mtr/mtr_39_41_self_employment.feature
  features/mtr/mtr_40_employment_allowance.feature
  features/mtr/mtr_42_priority_debt_repayment.feature
  features/mtr/mtr_45_housing_benefit_gross.feature
  features/mtr/mtr_47_property_disregard_main_home.feature
  features/mtr/mtr_49_pensioner_capital_disregard.feature
  features/mtr/mtr_50_pensioner_disregard.feature
  features/mtr/mtr_56_asylum_support.feature
  features/mtr/pension_contribution/mtr_38_cash_transactions.feature
  features/mtr/pension_contribution/mtr_38_outgoings.feature
  features/mtr/pension_contribution/mtr_38_regular_transactions.feature
  features/mtr/student_debt_repayment/mtr_39_employment.feature
  features/mtr/student_debt_repayment/mtr_39_self_employment.feature
Labels: approved

#432 Fix flakey swaggerization check
  lib/tasks/rswag.rake
Labels: approved

#433 tweak cucumber fixture to not hard code property value
  features/mtr/mtr_32_51_subject_matter_of_dispute_disregard.feature
  features/mtr/mtr_47_property_disregard_main_home.feature
  features/step_definitions/api_request_steps.rb
Labels: approved

#434 LEP-407 document and test client involvement types from LFA
  app/constants/cfe_constants.rb
  app/lib/swagger_docs.rb
  app/models/proceeding_type.rb
  spec/cassettes/LegalFrameworkAPI_ThresholdWaivers/_call/successful_API_call/responds_to_calling_service_with_parsed_response.yml
  spec/factories/proceeding_type_factory.rb
  spec/models/proceeding_type_spec.rb
  spec/services/legal_framework_api/threshold_waivers_spec.rb
  swagger/v6/swagger.yaml
  swagger/v7/swagger.yaml
Labels: approved

#435 Lep 170 childcare exemption checker
  app/services/concerns/exemptable.rb
  app/services/remark_generators/amount_variation_checker.rb
  app/services/remark_generators/base_checker.rb
  app/services/remark_generators/frequency_checker.rb
  app/services/remark_generators/multi_benefit_checker.rb
  app/services/utilities/childcare_exemption_detector.rb
Labels: approved

#440 rename stray MTR test with different name to all the others
  features/mtr/mtr_45_housing_benefit_disposable.feature
Labels: approved

#441 Tidy request rerunner - use v6 API, and change readme
  README.md
  app/services/request_rerunner.rb
Labels: approved

#438 Test exception settings were the mirror image of correct ones
  .circleci/config.yml
  app/controllers/application_controller.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
Labels: approved

#428 LEP-410 rename net and gross housing costs
  Changelog.md
  app/lib/person_disposable_income_subtotals.rb
  app/lib/swagger_docs.rb
  app/services/calculators/housing_costs_calculator.rb
  app/services/collators/housing_costs_collator.rb
  app/services/decorators/v6/assessment_decorator.rb
  app/services/decorators/v6/disposable_income_result_decorator.rb
  app/services/decorators/v6/result_summary_decorator.rb
  app/services/decorators/v7/applicant_disposable_income_result_decorator.rb
  app/services/decorators/v7/assessment_decorator.rb
  app/services/decorators/v7/disposable_income_result_decorator.rb
  app/services/decorators/v7/result_summary_decorator.rb
  spec/requests/swagger_docs/v6/full_assessment_spec.rb
  spec/requests/swagger_docs/v7/full_assessment_spec.rb
  spec/requests/v6/assessments_controller/simple_spec.rb
  spec/services/calculators/housing_costs_calculator_spec.rb
  spec/services/collators/housing_costs_collator_spec.rb
  spec/services/decorators/v6/disposable_income_result_decorator_spec.rb
  swagger/v6/swagger.yaml
  swagger/v7/swagger.yaml
Labels: approved

#437 Added test for invalid cash transactions
  spec/requests/v6/assessments_controller/errors_spec.rb
Labels: ready for review

#431 LEP-321 Remove DB remarks creation
  app/controllers/v6/assessments_controller.rb
  app/models/assessment.rb
  app/models/explicit_remark.rb
  app/services/decorators/v6/assessment_decorator.rb
  app/services/decorators/v6/remarks_decorator.rb
  app/services/redact_service.rb
  app/services/remarks.rb
  config/application.rb
  config/initializers/remarks.rb
  db/migrate/20231114183951_remove_column_remarks_from_assessments.rb
  db/schema.rb
  spec/factories/request_log_factory.rb
  spec/models/assessment_spec.rb
  spec/models/explicit_remark_spec.rb
  spec/services/decorators/v6/assessment_decorator_spec.rb
  spec/services/decorators/v6/remarks_decorator_spec.rb
  spec/services/redact_service_spec.rb
  spec/services/remarks_spec.rb
  spec/spec_helper.rb
Labels: question

#447 LEP-410 Housing Benefit - more renames
  app/services/calculators/housing_costs_calculator.rb
  app/services/calculators/state_benefits_calculator.rb
Labels: approved

#450 Remove nesty gem and tidy up
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  app/services/govuk_bank_holiday_retriever.rb
Labels: approved

#451 Lep 331 cash txn invalid date test
  app/services/creators/cash_transactions_creator.rb
  spec/requests/v6/assessments_controller/errors_spec.rb
Labels: approved

#449 LEP-326 Remove input 'other_income_sources/payments' from db
  app/controllers/v6/assessments_controller.rb
  app/models/gross_income_summary.rb
  app/models/other_income_payment.rb
  app/models/other_income_source.rb
  app/models/person_data.rb
  app/services/collators/gross_income_collator.rb
  app/services/creators/full_assessment_creator.rb
  app/services/creators/other_incomes_creator.rb
  app/services/creators/partner_financials_creator.rb
  app/services/remark_generators/orchestrator.rb
  app/services/workflows/non_passported_workflow.rb
  db/migrate/20231122113057_remove_tables_other_income_payments_and_other_income_sources.rb
  db/schema.rb
  spec/factories/assessment_factory.rb
  spec/factories/gross_income_summary_factory.rb
  spec/factories/other_income_payment_factory.rb
  spec/factories/other_income_source_factory.rb
  spec/factories/person_details_factory.rb
  spec/models/other_income_payment_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
  spec/services/creators/other_incomes_creator_spec.rb
  spec/services/cull_stale_assessments_service_spec.rb
  spec/services/remark_generators/frequency_checker_spec.rb
  spec/services/remark_generators/orchestrator_spec.rb
  spec/services/workflows/main_workflow_spec.rb
Labels: question

#430 LEP-349 don't short-circuit when ineligible
  app/lib/capital/unassessed.rb
  app/lib/capital/unassessed_with_partner.rb
  app/models/capitals_data.rb
  app/services/workflows/main_workflow.rb
  app/services/workflows/non_passported_workflow.rb
  features/mtr/mtr_45_housing_benefit_gross.feature
  spec/integration/test_runner_spec.rb
  spec/services/decorators/v6/assessment_decorator_spec.rb
  spec/spec_helper.rb
Labels: approved

#446 LEP-327 remove regular transactions from DB
  app/controllers/v6/assessments_controller.rb
  app/models/gross_income_summary.rb
  app/models/person_data.rb
  app/models/regular_transaction.rb
  app/services/calculators/housing_costs_calculator.rb
  app/services/calculators/monthly_regular_transaction_amount_calculator.rb
  app/services/calculators/state_benefits_calculator.rb
  app/services/collators/gross_income_collator.rb
  app/services/collators/housing_benefits_collator.rb
  app/services/collators/housing_costs_collator.rb
  app/services/collators/outgoings_collator.rb
  app/services/collators/regular_outgoings_collator.rb
  app/services/creators/full_assessment_creator.rb
  app/services/creators/partner_financials_creator.rb
  app/services/creators/regular_transactions_creator.rb
  app/services/remark_generators/payment_checker.rb
  app/services/workflows/non_passported_workflow.rb
  db/migrate/20231122152733_remove_regular_transactions.rb
  db/schema.rb
  spec/factories/person_details_factory.rb
  spec/factories/regular_transaction_factory.rb
  spec/models/gross_income_summary_spec.rb
  spec/models/regular_transaction_spec.rb
  spec/services/calculators/housing_costs_calculator_spec.rb
  spec/services/calculators/state_benefits_calculator_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
  spec/services/collators/housing_benefits_collator_spec.rb
  spec/services/collators/housing_costs_collator_spec.rb
  spec/services/collators/regular_outgoings_collator_spec.rb
  spec/services/creators/partner_financials_creator_spec.rb
  spec/services/creators/regular_transactions_creator_spec.rb
  spec/services/cull_stale_assessments_service_spec.rb
  spec/services/remark_generators/orchestrator_spec.rb
  spec/services/remark_generators/payment_checker_spec.rb
  spec/services/workflows/main_workflow_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
  spec/spec_helper.rb
Labels: approved

#439 LEP-406 Rails 7.1 upgrade
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  bin/rails
  bin/rake
  bin/setup
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/content_security_policy.rb
  config/initializers/cors.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/initializers/rswag_ui.rb
  features/mtr/mtr_31_32_46_income_capital_thresholds.feature
  spec/rails_helper.rb
  spec/support/error_responses.rb
Labels: approved

#448 LEP-330 remove irregular table
  app/controllers/v6/assessments_controller.rb
  app/lib/person_gross_income_subtotals.rb
  app/models/gross_income_summary.rb
  app/models/irregular_income_payment.rb
  app/models/person_data.rb
  app/services/collators/gross_income_collator.rb
  app/services/creators/full_assessment_creator.rb
  app/services/creators/irregular_income_creator.rb
  app/services/creators/partner_financials_creator.rb
  app/services/workflows/non_passported_workflow.rb
  db/migrate/20231123113144_remove_irregular_transactions.rb
  db/schema.rb
  spec/factories/gross_income_summary_factory.rb
  spec/factories/irregular_income_payment_factory.rb
  spec/factories/person_details_factory.rb
  spec/models/irregular_income_payment_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
  spec/services/creators/irregular_income_creator_spec.rb
  spec/services/creators/partner_financials_creator_spec.rb
  spec/services/cull_stale_assessments_service_spec.rb
  spec/services/decorators/v6/applicant_gross_income_result_decorator_spec.rb
  spec/services/decorators/v6/assessment_decorator_spec.rb
  spec/services/decorators/v6/gross_income_decorator_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
  spec/spec_helper.rb
Labels: approved

#452 LEP-349 Update Changelog.md
  Changelog.md
Labels: approved

#453 LEP-421 Rename "pending" result to "not_calculated"
  .circleci/config.yml
  Changelog.md
  app/lib/gross_income/unassessed.rb
  app/services/creators/capital_eligibility_creator.rb
  app/services/creators/disposable_income_eligibility_creator.rb
  app/services/utilities/result_summarizer.rb
  spec/factories/capital_summary_factory.rb
  spec/services/utilities/result_summarizer_spec.rb
Labels: approved
