Repository ministryofjustice/cfe-civil, pull requests merged in 2025-03, with the labels that each got.

#750 EL-2100 convert spreadsheet test to python
  features/BBB_CFE_Integration_Test_V3_Passported/P1-3-V5.feature
  features/BBB_CFE_Integration_Test_V3_Passported/P1-4-V5.feature
  features/BBB_CFE_Integration_Test_V3_Passported/P3-1-V5.feature
  features/BBB_CFE_Integration_Test_V3_Passported/P3-2-V5.feature
  features/BBB_CFE_Integration_Test_V3_Passported/P4-V5.feature
  features/BBB_CFE_Integration_Test_V3_Passported/P5-V5.feature
  features/BBB_CFE_Integration_Test_V3_Passported/P6-V5.feature
Labels: Approved

#745 [Snyk] Security upgrade net-imap from 0.5.5 to 0.5.6
  Gemfile
  Gemfile.lock
Labels: Approved

#759 EL-2156: Convert passported (DDD) tests to cucumber
  .circleci/config.yml
  features/BBB_CFE_Integration_Test_V3_Passported/P1-3-V5.feature
  features/BBB_CFE_Integration_Test_V3_Passported/P1-4-V5.feature
  features/BBB_CFE_Integration_Test_V3_Passported/P3-1-V5.feature
  features/BBB_CFE_Integration_Test_V3_Passported/P3-2-V5.feature
  features/BBB_CFE_Integration_Test_V3_Passported/P4-V5.feature
  features/BBB_CFE_Integration_Test_V3_Passported/P5-V5.feature
  features/BBB_CFE_Integration_Test_V3_Passported/P6-V5.feature
  features/CCC_CFE_Integration_Test_V3/NPE10-4-V5.feature
  features/DDD_CFE_Integration_Test_V3_Mortgage/MortNP1-V5.feature
  features/DDD_CFE_Integration_Test_V3_Mortgage/MortNP2-V5.feature
  features/DDD_CFE_Integration_Test_V3_Mortgage/MortNP3-V5.feature
  features/DDD_CFE_Integration_Test_V3_Mortgage/MortNP4-V5.feature
  features/DDD_CFE_Integration_Test_V3_Mortgage/MortNP5-V5.feature
  features/DDD_CFE_Integration_Test_V3_Mortgage/MortNP6-V5.feature
  features/DDD_CFE_Integration_Test_V3_Mortgage/MortP1-V5.feature
  features/DDD_CFE_Integration_Test_V3_Mortgage/MortP2-V5.feature
  features/DDD_CFE_Integration_Test_V3_Mortgage/MortP3-V5.feature
  features/DDD_CFE_Integration_Test_V3_Mortgage/MortP4-V5.feature
  features/DDD_CFE_Integration_Test_V3_Mortgage/MortP5-V5.feature
  features/DDD_CFE_Integration_Test_V3_Mortgage/MortP6-V5.feature
  features/step_definitions/api_request_steps.rb
Labels: Approved, UAT

#755 EL-2127: add new thresholds configuration file.
  README.md
  config/thresholds/2025-04-07.yml
  config/thresholds/values.yml
  features/dependant/dependant_income.feature
  features/partner/partner_assessment.feature
  spec/models/threshold_spec.rb
Labels: Approved, DO NOT MERGE

#771 EL-2179: Convert passported (EEE) tests to cucumber
  features/EEE_CFE_Integration_Test_V3_Pensioner_Capital/NP_Pens1-V5.feature
  features/EEE_CFE_Integration_Test_V3_Pensioner_Capital/NP_Pens2-V5.feature
  features/step_definitions/api_request_steps.rb
Labels: Approved
